name: Cache Video

on:
  workflow_dispatch:
    inputs:
      youtube_link:
        type: string
        required: true
        description: youtube video link
        default: https://www.youtube.com/watch?v=PDEP1483BN8

jobs:
  cache_video:
    name: Cache Video
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/cache@v2
      id: cache_video
      with:
        path: video.mp4
        key: video
    - name: Setup youtube-dl
      if: steps.cache_video.outputs.cache-hit != 'true'
      uses: AnimMouse/setup-youtube-dl@v1
    - name: download youtube video
      if: steps.cache_video.outputs.cache-hit != 'true'
      run: youtube-dl ${{ github.event.inputs.youtube_link }} -o video.mp4