on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - master

jobs:
  download_dataset:
    name: download_dataset
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        goodle_drive_file_id: [1FMCPw5fD9Sl-0eTXhb6FS6YBDkaSIyTB]
    steps:
    - uses: actions/cache@v2
      id: cache_dataset
      with:
        path: images.zip
        key: images-${{ matrix.goodle_drive_file_id }}
    - name: Set up Python
      if: steps.cache_dataset.outputs.cache-hit != 'true'
      uses: actions/setup-python@v1
      with:
        python-version: "3.6.15"
    - name: Install
      if: steps.cache_dataset.outputs.cache-hit != 'true'
      run: pip3 install gdown
    - name: Download dataset
      if: steps.cache_dataset.outputs.cache-hit != 'true'
      run: gdown ${{ matrix.goodle_drive_file_id }} -O images.zip
  convert_to_coco:
    name: convert_to_coco
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        goodle_drive_file_id: [1FMCPw5fD9Sl-0eTXhb6FS6YBDkaSIyTB]
    steps:
    - uses: actions/checkout@v2-beta
    - name: Set up Python
      if: steps.cache_dataset.outputs.cache-hit != 'true'
      uses: actions/setup-python@v1
      with:
        python-version: "3.6.15"
    - uses: actions/cache@v2
      id: cache_dataset
      with:
        path: images.zip
        key: images-${{ matrix.goodle_drive_file_id }}
    - name: Unzip images
      run: unzip images.zip && mv images/* .