name: Inference
on:
  workflow_dispatch:
    inputs:
      image_url:
        default: https://user-images.githubusercontent.com/10348912/187019282-cc068be6-b7c3-4507-8615-11e8f9b3f1dd.JPG
        type: string
        required: false
        description: URL of the image
      model:
        description: model name
        required: false
        type: choice
        options:
          - yolox_nano
          - yolox_s
        default: yolox_nano

jobs:
  inference:
    runs-on: ubuntu-latest
    container:
      image: wamvtan/yolox:latest
    steps:
      - name: download script
        run: https://github.com/OUXT-Polaris/YOLOX/blob/file-yolox-exps/tools/ouxt_demo.py
      - name: download image
        run : wget ${{ github.event.inputs.model }}.
      - name: check files
        run: ls
      - name: check directory
        run: pwd
