name: Inference
on:
  workflow_dispatch:
    inputs:
      image_url:
        default: https://user-images.githubusercontent.com/10348912/187019282-cc068be6-b7c3-4507-8615-11e8f9b3f1dd.JPG
        type: string
        required: false
        description: URL of the image
      model:
        description: model name
        required: false
        type: choice
        options:
          - yolox_nano
          - yolox_s
        default: yolox_nano
      version:
        default: latest
        type: string
        required: false
        description: version of model

jobs:
  inference:
    name: Inference
    runs-on: [self-hosted, yolox_trainer]
    steps:
    - name: Cleanup
      run: |
        rm -rf *
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: OUXT-Polaris/dataset_annotations
        version: ${{ github.event.inputs.version }}
        file: ${{ github.event.inputs.model }}.pth
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: download script
      run: https://github.com/OUXT-Polaris/YOLOX/blob/file-yolox-exps/tools/ouxt_demo.py
    - name: download image
      run : wget ${{ github.event.inputs.image_url }}
