name: train
on:
  workflow_dispatch:
    inputs:
      dataset_version:
        default: latest
        type: string
        required: false
        description: version of dataset
jobs:
  build:
    name: Build
    runs-on: [self-hosted, yolox_trainer]
    steps:
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: OUXT-Polaris/dataset_annotations
        version: ${{ github.event.inputs.dataset_version }}
        file: coco.zip
        token: ${{ secrets.GITHUB_TOKEN }}