name: Train
on:
  workflow_dispatch:
    inputs:
      dataset_version:
        default: latest
        type: string
        required: false
        description: version of dataset
jobs:
  build:
    name: Build
    runs-on: [self-hosted, yolox_trainer]
    steps:
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: OUXT-Polaris/dataset_annotations
        version: ${{ github.event.inputs.dataset_version }}
        file: coco.zip
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: unzip dataset
      run: |
        unzip coco.zip
        mkdir ouxt-2022-dataset
        mv coco/* ouxt-2022-dataset
        cd ouxt-2022-dataset
        mv test.json validation.json
        mkdir train2017 val2017 annotations
        cp -r JPEGImages train2017/
        cp -r JPEGImages val2017/
        mv validation.json ./annotations
        mv train.json ./annotations